const ACTION_TYPES = {
    WEATHER: {
        GET_WEATHER_START: 'GET_WEATHER_START',
        GET_WEATHER_FAILED: 'GET_WEATHER_FAILED',
        GET_WEATHER_SUCCESS: 'GET_WEATHER_SUCCESS',
    }
}

export default ACTION_TYPES